name: Simulation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: hipas/gridlabd:latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Run simulation
      run: gridlabd main.glm
      
    - name: Save results
      uses: actions/upload-artifact@v3
      with:
        name: location data
        path: location-data.png
        
      
